---
- name: Instala o Docker, Docker-compose no Ubuntu
  hosts: docker_server
  become: yes
  tasks:
    - name: Atualiza os pacotes do APT
      apt:
        update_cache: true

    - name: Instala dependências necessárias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Adiciona chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adiciona repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instala o Docker
      apt:
        name: docker-ce
        state: present

    - name: Instala o docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{ lookup('pipe', 'uname -m') }}
        dest: /usr/local/bin/docker-compose
        mode: '+x'

    - name: Inicia o daemon do Docker
      systemd:
        name: docker
        state: started
    - name: Instala pip3
      apt:
        name: python3-pip
        state: present

    - name: Instala módulos Python do docker
      pip:
        name:
          - docker
          - docker-compose
        executable: pip3

- name: Adiciona usuário ubuntu ao grupo docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Adiciona usuário ubuntu ao grupo docker
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Reconecta à sessão do servidor
      meta: reset_connection

- name: Inicia os contêineres do Docker
  hosts: docker_server
  tasks:
    - name: Copia o arquivo docker-compose
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml # caminho atualizado para o usuário Ubuntu
    - name: Inicia o contêiner
      docker_compose:
        project_src: /home/ubuntu # caminho atualizado para o usuário Ubuntu
        state: present
